modular/max

- examples/tools/benchmark-pytorch/run.sh
- examples/tools/benchmark-tensorflow/run.sh
- examples/tools/common/roberta-pytorch/.gitignore
- examples/tools/common/roberta-pytorch/download-model.py
- examples/tools/common/roberta-pytorch/download-model.sh
- examples/tools/common/roberta-pytorch/input-spec.yaml
- examples/tools/common/roberta-tensorflow/.gitignore
- examples/tools/common/roberta-tensorflow/download-model.py
- examples/tools/common/roberta-tensorflow/download-model.sh
- examples/tools/common/roberta-tensorflow/input-spec.yaml
ResNet-50 currently takes longer to compile than RoBERTa does.  Swap out the model to RoBERTa so the user spends less time waiting for model compilation.  We'd switch the visualize example too, but RoBERTa is a more complicated model that pushes the limits of Netron -- ResNet-50 is more reasonably sized and works better with Netron, even though it takes longer to compile in MAX.
> Switch benchmark example to RoBERTa

- examples/inference/bert-c-tensorflow/README.md
- examples/inference/bert-c-torchscript/README.md
- examples/inference/bert-python-torchscript/README.md
- examples/inference/resnet50-python-tensorflow/README.md
- examples/inference/roberta-python-tensorflow/README.md
- examples/inference/stablediffusion-mojo-tensorflow/README.md
- examples/inference/stablediffusion-python-tensorflow/README.md
It may throw an error on some OSes and architectures (Ubuntu 20 on Graviton) if there's an old `setuptools` installed. So we upgrade it before installing dependencies from `requirements.txt`.
The version range in `requirements.txt` is not enough because pip installs dependencies from `requirements.txt` all at once using older `setuptools`.
I'll keep the version range in `requirements.txt` as a "message" for users.
> Update setuptools before installing dependencies from requirements.txt

- examples/console.py
For python3.8, there seems to be a bug related `os.path.dirname(__file__)` returning empty string which using `pathlib.Path` fixes it.
> Make console ROOT universal

- examples/performance-showcase/requirements.txt
- examples/performance-showcase/run.py
Relying on cpuinfo was an expedient but brittle approach to providing some system information along with the performance comparison printout. 
This PR fixes #18 by failing gracefully if the host os doesn't expose the basic information we want to present (instead of crashing).
> Fix #18 cpuinfo not found crash

- .github/ISSUE_TEMPLATE/CODEOWNERS
This PR introduces a `CODEOWNERS` file in the MAX repo. Modulers who are added to the `max-code-reviewers` team will be automatically subscribed to all code reviews made against this public repository. We can also adjust granularity wrt functional scope demonstrated in this repo in the future.
> Add initial CODEOWNERS file to max repo

- examples/inference/bert-python-torchscript/simple-inference.py
- examples/inference/resnet50-python-tensorflow/simple-inference.py
- examples/inference/roberta-python-tensorflow/simple-inference.py
- examples/inference/stablediffusion-mojo-tensorflow/download-model.py
- examples/inference/stablediffusion-python-tensorflow/download-model.py
We move max.engine imports to the top of each source file due to a documented [issue here](https://docs.beta.modular.com/engine/roadmap#pytorch-error-cannot-allocate-memory-in-static-tls-block)
> Move max.engine import order to top of source files

- examples/inference/stablediffusion-python-tensorflow/text-to-image.py
We have seen some TLS issues manifest when the Max engine is imported after KerasCV. While the root cause is under investigation, moving this import line should reduce errors in the common case of simply running our examples.
> Move max import statements up ahead of Keras

- examples/inference/bert-python-torchscript/triton-inference.py
- examples/inference/resnet50-python-tensorflow/triton-inference.py
- examples/inference/stablediffusion-mojo-tensorflow/tokenizer.py
- examples/inference/stablediffusion-python-tensorflow/download-model.py
Run `black` on Python source files and remove an extra `from max import engine` call in the Stable Diffusion Python TensorFlow example
> Run black to fix file formatting and remove redundant max.engine import

- examples/tools/visualize-pytorch/run.sh
- examples/tools/visualize-tensorflow/run.sh
`python3 -m webbrowser https://netron.app` command requires interaction from a user. We skip it if we execute the code in CI. CI systems set the `$CI` variable to true, e.g. [GitHub](https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables)
> Do not open web browser if in CI

- .gitignore
- examples/inference/stablediffusion-mojo-tensorflow/.gitignore
- examples/inference/stablediffusion-mojo-tensorflow/run.sh
- examples/inference/stablediffusion-mojo-tensorflow/text-to-image.🔥
- examples/inference/stablediffusion-python-tensorflow/.gitignore
- examples/inference/stablediffusion-python-tensorflow/run.sh
- examples/inference/stablediffusion-python-tensorflow/text-to-image.py
This is a first of `N` PRs moves a subset of downloaded example models into a central, gitignored `models` subdirectory. By the end of it, we won't have to re-download the same models across different examples / scripts within this repository.
This PR covers `Stable Diffusion` examples within the `inference` subdirectory.
The gitignored `models` subdirectory looks something like this when most examples are run:
Stable Diffusion
> Stable Diffusion: Consolidate model downloads into a top level, gitignored directory [1/N]

- examples/graph-api/llama2/setup.sh
This is really annoying, if you source this it applies to your main shell which is bad news.
> [Graph API] Don't `set -e` in setup

- examples/performance-showcase/common.py
Subsequent calls to subprocess were not getting the ENV and stderr options plumbed through to, which caused some collision on printouts.
> Minor bugfix in performance-showcase example (fix output bugs)

- examples/inference/roberta-python-tensorflow/.gitignore
- examples/inference/roberta-python-tensorflow/README.md
- examples/inference/roberta-python-tensorflow/deploy.sh
- examples/inference/roberta-python-tensorflow/download-model.py
- examples/inference/roberta-python-tensorflow/run.sh
- examples/inference/roberta-python-tensorflow/simple-inference.py
- examples/tools/benchmark-pytorch/run.sh
- examples/tools/benchmark-tensorflow/run.sh
- examples/tools/common/resnet50-pytorch/.gitignore
- examples/tools/common/resnet50-tensorflow/.gitignore
- examples/tools/common/roberta-pytorch/.gitignore
- examples/tools/common/roberta-tensorflow/.gitignore
This is 2 of `N` PRs moves a subset of downloaded example models into a central, gitignored `models` subdirectory. By the end of it, we won't have to re-download the same models across different examples / scripts within this repository.
This PR covers `RoBERTa` examples within `inference/` and `tools/`. We skip `notebooks/` for now as that is a standalone workflow that doesn't rely on a prior downloaded model.
The gitignored `models` subdirectory looks something like this when most examples are run:
NOTE: I did not make any changes to `deploy.sh` and `triton-inference.py` in this PR. They will keep their download model workflow respectively, at least for now.
PyTorch benchmark:
TensorFlow benchmark:
1. #52
> RoBERTa: Consolidate common, downloaded models into a top level, gitignored directory [2/N]

- examples/inference/bert-python-torchscript/deploy.sh
- examples/inference/resnet50-python-tensorflow/deploy.sh
- examples/inference/roberta-python-tensorflow/deploy.sh
MAX Serving images are now available under `public.ecr.aws/modular/max-serving-de`. This PR changes the examples to point to that registry. The browsable link to the registry https://gallery.ecr.aws/modular/max-serving-de
> Migrate MAX Serving images to a public ECR with the modular alias

- examples/inference/bert-python-torchscript/run.sh
This PR fixes a `$MODEL_PATH` env variable bug in BERT Python TorchScript example. This env variable fails to "follow" where the `run.sh` script is run from. There was also another bug around `simple-inference.py` where we implicitly depend on running it on the same subdirectory level as `run.sh`. While this is true, it would break almost immediately any other directory level.
> Fix model path in BERT python torchscript run.sh

- examples/performance-showcase/run.py
- examples/performance-showcase/run_max.py
- examples/performance-showcase/run_pt.py
- examples/performance-showcase/run_tf.py
Without it the package was imported in `test_requirements` function after other packages and caused the TLS problem.
Details about the TLS issue: https://docs.modular.com/engine/roadmap#pytorch-error-cannot-allocate-memory-in-static-tls-block
> Add import of max engine to the beginning of run.py to avoid the TLS issue).

- examples/inference/stablediffusion-mojo-tensorflow/text-to-image.🔥
Fix a small typo in our Mojo Stable Diffusion example script.
> Fix Stable Diffusion Mojo parse arg typo

- examples/graph-api/llama2/model/llama.🔥
- examples/graph-api/llama2/run.🔥
- examples/graph-api/llama2/tokenizer/ball.🔥
- examples/graph-api/llama2/tokenizer/bpe.🔥
- examples/graph-api/llama2/tokenizer/max_heap.🔥
- examples/graph-api/llama2/weights/gguf.🔥
- examples/inference/stablediffusion-mojo-tensorflow/python_utils.🔥
- examples/inference/stablediffusion-mojo-tensorflow/text-to-image.🔥
As DynamicVector was renamed to List in the latest iteration of the Mojo SDK, max examples started being out of date. This patch fixes that.
Fixes https://github.com/modularml/modular/issues/33434
> Bring examples up to speed to latest Mojo-SDK

- examples/inference/bert-c-tensorflow/download-model.py
- examples/inference/bert-c-tensorflow/run.sh
Adding "-o" option to BERT C example for consistency.
> Use consistent output args in all inference examples. 

- examples/inference/bert-c-tensorflow/README.md
- examples/inference/bert-c-torchscript/README.md
- examples/inference/bert-python-torchscript/README.md
- examples/inference/resnet50-python-tensorflow/README.md
- examples/inference/roberta-mojo-tensorflow/README.md
- examples/inference/roberta-python-tensorflow/README.md
- examples/inference/stablediffusion-mojo-tensorflow/README.md
- examples/inference/stablediffusion-python-tensorflow/README.md
It appears some text was copy-pasted and wasn't correct for the example, and there was some incorrect product terminology. 
This also adds a link to the MAX Engine get started before trying to run any of the examples, puts all code snippets into code blocks for usability, improves page titles, and adds formatting to line length to make future diffs simpler and easier to comment upon in PRs.
> Add corrections, clarity, and cleanup to inference READMEs
